# For reference: https://alacritty.org/config-alacritty.html

# Colors (Solarized Light) from https://github.com/alacritty/alacritty-theme/blob/master/themes/solarized_light.toml

# Default colors
[colors.primary]
background = '#fdf6e3'
foreground = '#586e75'

# Normal colors
[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

# Bright colors
[colors.bright]
black   = '#002b36'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'

# --

# custom cursor for alacritty+zsh reasons (zsh reverse, cursor reverses again)
# Watching: https://github.com/alacritty/alacritty/issues/5662
# Also: https://stackoverflow.com/questions/61776558/zsh-in-vi-mode-how-to-change-color-scheme
[colors.cursor]
cursor = "0x073642"
text = "0xeee8d5"

[cursor.style]
blinking = "Never"

# True color support: https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
[env]
TERM = "xterm-256color"

[font]
# default is 11
size = 13.0

[font.normal]
# family = Monaco
family = "Monego Nerd Font Fix"

[window]
decorations = "none"
