schemes:
  solarized_light: &solarized_light
    # Default colors
    primary:
      background: '0xfdf6e3'
      foreground: '0x586e75'

    # Normal colors
    normal:
      black:   '0x073642'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0xeee8d5'

    # Bright colors
    bright:
      black:   '0x002b36'
      red:     '0xcb4b16'
      green:   '0x586e75'
      yellow:  '0x657b83'
      blue:    '0x839496'
      magenta: '0x6c71c4'
      cyan:    '0x93a1a1'
      white:   '0xfdf6e3'

    # custom cursor for alacritty+zsh reasons (zsh reverse, cursor reverses again)
    # example: https://github.com/alacritty/alacritty/blob/master/alacritty.yml
    # Watching: https://github.com/alacritty/alacritty/issues/5662
    # Also: https://stackoverflow.com/questions/61776558/zsh-in-vi-mode-how-to-change-color-scheme
    cursor:
      #text: CellBackground
      #cursor: CellForeground
      cursor: '0x073642' # black
      text: '0xeee8d5' #white

colors: *solarized_light

# True color support: https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
env:
  TERM: xterm-256color

font:
  normal:
    #family: Monaco
    family: Monego Nerd Font Fix

  # Default is 11
  size: 13.0

cursor:
  style:
    blinking: Never

window:
  decorations: none
