const fs = require("fs");

const allCmds = [
  {
    name: "cdg",
    cmds: [
      {
        cmdTrigger: "cdg ",
        cmdListOptions: "git ls-files $(git rev-parse --show-toplevel) | awk -F/ '{OFS=\"/\"; $NF=\"\"; print $0}' | sort -u",
        fzfOptions: "--preview 'tree -C {} | head -200'"
      }
    ]
  },
  {
    name: "cdw",
    cmds: [
      {
        cmdTrigger: "cdw ",
        cmdListOptions: "ls -d ~/workspace/*/",
        fzfOptions: "--preview 'tree -C {} | head -200'"
      }
    ]
  },
  {
    name: "cdws",
    cmds: [
      {
        cmdTrigger: "cdws ",
        cmdListOptions: "ls -d ~/ws/*/",
        fzfOptions: "--preview 'tree -C {} | head -200'"
      }
    ]
  },
  {
    name: "brew",
    cmds: [
      {
        cmdTrigger: "brew install --cask ",
        // cmdListOptions: 'brew search --casks',
        cmdListOptions: 'cache_fzf.js "brew install --cask"',
        fzfOptions: "--multi --preview 'brew info --cask {}'"
      },
      {
        cmdTrigger: "brew install ",
        // cmdListOptions: 'brew formulae',
        cmdListOptions: 'cache_fzf.js "brew install"',
        fzfOptions: "--multi --preview 'brew info {}'"
      },
      {
        cmdTrigger: "brew uninstall --cask ",
        cmdListOptions: "brew list --cask",
        fzfOptions: "--multi --preview 'brew info --cask {}'"
      },
      {
        cmdTrigger: "brew uninstall ",
        cmdListOptions: "brew list --formula",
        fzfOptions: "--multi --preview 'brew info {}'"
      }
    ]
  },
  {
    name: "pip",
    cmds: [
      {
        cmdTrigger: "pip uninstall",
        cmdListOptions: `pip list 2> /dev/null | tail -n +3 | awk '{print $1}' | rg -v '^(setuptools|wheel)$'`,
        fzfOptions: `--multi --preview 'pip show {}'`
      }
    ]
  },
  {
    name: "docker",
    cmds: [
      {
        cmdTrigger: "docker rm ",
        cmdListOptions: `docker ps -a`,
        fzfOptions: "--multi",
        postColumn: "1"
      },
      {
        cmdTrigger: "docker image rm ",
        cmdListOptions: `docker images -a`,
        fzfOptions: "--multi",
        postColumn: "3"
      },
      {
        cmdTrigger: "docker volume rm ",
        cmdListOptions: `docker volume ls`,
        fzfOptions: "--multi",
        postColumn: "2"
      }
    ]
  },
  {
    name: "gulp",
    cmds: [
      {
        cmdTrigger: "gulp ",
        cmdListOptions: "cache_fzf.js 'gulp'",
        fzfOptions: "--multi"
      }
    ]
  },
  // {
  //   name: "bazel",
  //   cmds: [
  //     {
  //       cmdTrigger: "bazel build ",
  //       cmdListOptions:
  //         'bazel query "$(echo "$LBUFFER" | awk \'{print $3}\')"... 2> /dev/null',
  //       fzfOptions: "--multi --preview \"bazel query 'deps({})' 2> /dev/null\""
  //       // '--multi --preview "bazel query \'kind(\\"source file\\", deps({}))\' 2> /dev/null"'
  //     }
  //   ]
  // }
];

function generateFunc(name, cmds) {
  return `
_fzf_complete_${name}() {
  ARGS="$@"
  ${cmds
    .map(
      ({ cmdTrigger, cmdListOptions, fzfOptions }) =>
        `if [[ $ARGS == '${cmdTrigger}'* ]]; then
    local options="$(${cmdListOptions})"
    _fzf_complete ${fzfOptions} -- "$@" < <(
      echo $options
    )`
    )
    .join("\n  el")}
  else
    return 1
  fi
}
${generatePostProcessing(name, cmds)}
  `.trim();
}
function generatePostProcessing(name, cmds) {
  cmds = cmds.filter(({ postColumn }) => postColumn);
  if (!cmds.length) {
    return "";
  }
  return `
_fzf_complete_${name}_post() {
  ${cmds
    .map(
      ({ cmdTrigger, postColumn }) =>
        `if [[ $ARGS == '${cmdTrigger}'* ]]; then
    awk '{print $${postColumn}}'`
    )
    .join("\n  el")}
  else
    return 1
  fi
}
  `.trim();
}
const result = allCmds
  .map(({ name, cmds }) => generateFunc(name, cmds))
  .join("\n");
const header = `
## AUTOGENERATED
## fzf examples - completion
# https://github.com/junegunn/fzf/wiki/Examples-(completion)
`.trim();

const fileContents = `${header}\n\n${result}`;
fs.writeFileSync(".zsh-fzf-comp.zsh", fileContents);
